packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@better-auth/api-key": 1.5.4
  "@better-auth/expo": 1.5.4
  "@eslint/js": ^9.39.4
  "@heroicons/react": 2.2.0
  "@heroui/react": ^2.8.10
  "@scalar/nextjs-api-reference": ^0.10.6
  "@tailwindcss/postcss": ^4.2.2
  "@tanstack/react-query": ^5.95.2
  "@testcontainers/postgresql": ^11.13.0
  "@trpc/client": ^11.15.1
  "@trpc/server": ^11.15.1
  "@trpc/tanstack-react-query": ^11.15.1
  "@types/node": ^25.5.0
  "@types/react": 19.2.14
  "@types/react-dom": 19.2.3
  "@vitejs/plugin-react": ^5.2.0
  better-auth: 1.5.4
  bullmq: ^5.71.1
  date-fns: ^4.1.0
  drizzle-orm: 0.45.1
  eslint: 9.39.1
  fuse.js: ^7.1.0
  html-entities: ^2.6.0
  ioredis: ^5.10.1
  jsdom: ^28.1.0
  jszip: 3.10.1
  next: 16.1.6
  pg: 8.18.0
  postcss: ^8.5.8
  prettier: ^3.8.1
  react: 19.2.4
  react-dom: 19.2.4
  server-only: ^0.0.1
  superjson: ^2.2.6
  tailwindcss: ^4.2.2
  trpc-to-openapi: ^3.2.0
  turbo: ^2.8.20
  typescript: 5.9.3
  vite: ^7.1.12
  vitest: ^4.1.2
  ws: 8.19.0
  zod: 4.3.6
  zod-openapi: ^5.4.2

injectWorkspacePackages: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - "@heroui/shared-utils"
  - esbuild
  - ffmpeg-static
  - sharp
  - unrs-resolver

patchedDependencies:
  expo-widgets@55.0.7: patches/expo-widgets@55.0.7.patch

syncInjectedDepsAfterScripts:
  - build
