#!/usr/bin/env sh

# Exit on errors and on use of undefined variables.
set -eu

# Resolve the directory that contains this script.
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ENV_FILE="${SCRIPT_DIR}/.env"

log() {
  printf '%s\n' "$*" >&2
}

# Best-effort Linux detection:
# ask the kernel which source IPv4 it would use for outbound traffic.
# This is often useful on plain Linux, but it is not guaranteed to be the
# phone-reachable LAN IP when running inside Docker/WSL.
detect_from_ip_route() {
  command -v ip >/dev/null 2>&1 || return 1

  ip -4 route get 1.1.1.1 2>/dev/null | awk '
    {
      for (i = 1; i <= NF; i++) {
        if ($i == "src") {
          print $(i + 1)
          exit
        }
      }
    }
  '
}

# Fallback: pick the first non-loopback IPv4 reported by hostname.
# This is still only best-effort.
detect_from_hostname() {
  command -v hostname >/dev/null 2>&1 || return 1

  hostname -I 2>/dev/null \
    | tr ' ' '\n' \
    | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' \
    | grep -v '^127\.' \
    | head -n 1
}

IP_ADDRESS=""

if [ -z "$IP_ADDRESS" ]; then
  IP_ADDRESS=$(detect_from_ip_route || true)
fi

if [ -z "$IP_ADDRESS" ]; then
  IP_ADDRESS=$(detect_from_hostname || true)
fi

# If we still do not know the right address, do not break container setup.
# Leave a clear message so user can set it explicitly.
if [ -z "$IP_ADDRESS" ]; then
  log "Could not determine REACT_NATIVE_PACKAGER_HOSTNAME automatically."
  log "If you want to use Expo set it in devcontainer.json manually and rebuild !"
  exit 0
fi

# Write the generated env file atomically.
TMP_FILE=$(mktemp "${ENV_FILE}.XXXXXX")

cat > "$TMP_FILE" <<EOF
# Generated by make_hostip_env_for_expo.sh.
# Do not add anything here, it gets overwritten on every devcontainer creation.
# To override, set REACT_NATIVE_PACKAGER_HOSTNAME in devcontainer.json containerEnv section
REACT_NATIVE_PACKAGER_HOSTNAME=${IP_ADDRESS}
EOF

mv "$TMP_FILE" "$ENV_FILE"

log "Wrote ${ENV_FILE} with REACT_NATIVE_PACKAGER_HOSTNAME=${IP_ADDRESS}"
